version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: micro_millenium_app
    env_file:
      - .env
      - .env.test
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    volumes:
      - .:/home/node/app
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - micro_millenium_db
      - micro_millenium_db_test
      - micro_millenium_redis

  micro_millenium_db:
    image: postgres:9.4
    container_name: micro_millenium_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/micro_millenium_db
    
  micro_millenium_db_test:
    image: postgres:9.4
    container_name: micro_millenium_db_test
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT_TEST}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/micro_millenium_db_test
  
  micro_millenium_redis:
    image: bitnami/redis:latest
    container_name: micro_millenium_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  cache:
    driver: local