export * from  './create-person.controller'
export * from  './get-person.controller'
export * from  './get-all-persons.controller'
export * from  './list-persons.controller'
export * from  './delete-person.controller'
export * from  './update-person.controller'