export * from './create-education.controller'
export * from './delete-education.controller'
export * from './get-education.controller'
export * from './update-education.controller'
export * from './list-educations.controller'